<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[got google search bar and searched for : Vodafone<br>]]>
    </line>
    <line>
      <![CDATA[scrolled down to the end of the page successfully<br>]]>
    </line>
    <line>
      <![CDATA[clicked next button successfully<br>]]>
    </line>
    <line>
      <![CDATA[got results shown of the page<br>]]>
    </line>
    <line>
      <![CDATA[scrolled down to the end of the page successfully<br>]]>
    </line>
    <line>
      <![CDATA[clicked next button successfully<br>]]>
    </line>
    <line>
      <![CDATA[got results shown of the page<br>]]>
    </line>
    <line>
      <![CDATA[<br><br>screenshot of the failure : <br><br>]]>
    </line>
    <line>
      <![CDATA[<img src='failureScreenshots\firstTest.jpg' height='400' width='400'/>]]>
    </line>
    <line>
      <![CDATA[terminated the browser<br>]]>
    </line>
  </reporter-output>
  <suite started-at="2022-10-29T19:21:21Z" name="Default Suite" finished-at="2022-10-29T19:21:28Z" duration-ms="7171">
    <groups>
    </groups>
    <test started-at="2022-10-29T19:21:21Z" name="VOIS_Automation_Challenge" finished-at="2022-10-29T19:21:28Z" duration-ms="7171">
      <class name="TestClasses.SearchSizeTest">
        <test-method is-config="true" signature="start()[pri:0, instance:TestClasses.SearchSizeTest@16022d9d]" started-at="2022-10-29T19:21:21Z" name="start" finished-at="2022-10-29T19:21:23Z" duration-ms="1959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="firstTest()[pri:0, instance:TestClasses.SearchSizeTest@16022d9d]" started-at="2022-10-29T19:21:23Z" name="firstTest" finished-at="2022-10-29T19:21:28Z" duration-ms="4711" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [9] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [9] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at TestClasses.SearchSizeTest.firstTest(SearchSizeTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[got google search bar and searched for : Vodafone<br>]]>
            </line>
            <line>
              <![CDATA[scrolled down to the end of the page successfully<br>]]>
            </line>
            <line>
              <![CDATA[clicked next button successfully<br>]]>
            </line>
            <line>
              <![CDATA[got results shown of the page<br>]]>
            </line>
            <line>
              <![CDATA[scrolled down to the end of the page successfully<br>]]>
            </line>
            <line>
              <![CDATA[clicked next button successfully<br>]]>
            </line>
            <line>
              <![CDATA[got results shown of the page<br>]]>
            </line>
            <line>
              <![CDATA[<br><br>screenshot of the failure : <br><br>]]>
            </line>
            <line>
              <![CDATA[<img src='failureScreenshots\firstTest.jpg' height='400' width='400'/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method is-config="true" signature="terminate()[pri:0, instance:TestClasses.SearchSizeTest@16022d9d]" started-at="2022-10-29T19:21:28Z" name="terminate" finished-at="2022-10-29T19:21:28Z" duration-ms="419" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[terminated the browser<br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- terminate -->
      </class> <!-- TestClasses.SearchSizeTest -->
    </test> <!-- VOIS_Automation_Challenge -->
  </suite> <!-- Default Suite -->
</testng-results>
